<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pg.sql_query_helper' shared service.

include_once $this->targetDirs[3].'/src/PgBundle/Util/QueryHelper/QueryHelper.php';
include_once $this->targetDirs[3].'/src/PgBundle/Util/QueryHelper/SqlQueryHelper.php';

return $this->services['pg.sql_query_helper'] = new \PgBundle\Util\QueryHelper\SqlQueryHelper(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
