<?php

namespace AppBundle\Repository;

/**
 * PropiedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropiedadRepository extends \Doctrine\ORM\EntityRepository
{
}
