<?php

namespace AppBundle\Repository;

/**
 * CreditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditoRepository extends \Doctrine\ORM\EntityRepository
{
}
