<?php

namespace AppBundle\Repository;

/**
 * EstadoSubastaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoSubastaRepository extends \Doctrine\ORM\EntityRepository
{
}
