<?php

namespace AppBundle\Repository;

/**
 * EstadoCreditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCreditoRepository extends \Doctrine\ORM\EntityRepository
{
}
