<?php

namespace AppBundle\Repository;

/**
 * EstadoReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoReservaRepository extends \Doctrine\ORM\EntityRepository
{
}
