<?php

namespace AppBundle\Repository;

/**
 * HotSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotSaleRepository extends \Doctrine\ORM\EntityRepository
{
}
