<?php

namespace AppBundle\Repository;

/**
 * PujaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PujaRepository extends \Doctrine\ORM\EntityRepository
{
}
