<?php

namespace AppBundle\Repository;

/**
 * ReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByPropiedadAndSemana($prop,$sem,$anio)
	{
		return $this->createQueryBuilder('r')
			->join('r.propiedad','p')
            ->where('p.id = '.$prop)
            ->andWhere('r.semana = '.$sem)
            ->andWhere('r.anio = '.$anio)
            ->getQuery()
            ->getOneOrNullResult();
	}

	public function buildQuery($query, $pg)
	{
		$propiedad = $pg->getFilterValue('propiedad');

    $fechaMin = (new \DateTime("now"))->modify('+6 months');
		$fechaMin->modify('last monday');;
		
    $fechaMax = (new \DateTime("now"))->modify('+12 months');
		$fechaMax->modify('last monday');

    $query->join("a.propiedad","p")
  	  ->andWhere("a.fechaInicio >= :finicio")->setParameter('finicio', $fechaMin)
  	  ->andWhere("a.fechaFin <= :ffin")->setParameter('ffin', $fechaMax)
  	  ->andWhere("p.id = ".$propiedad)
    	->orderBy('a.fechaInicio');
        
	    return $query;
	}


  public function reservasDelUsuario($query, $pg)
  {

    $usuario = $pg->getFilterValue('usuario');

    $query->join("a.usuario","u")
      ->andWhere("u.id = :usuario")
      ->andWhere("a.estado != 3")
      ->setParameter('usuario', $usuario);
        
      return $query;
  }

}
