<?php

namespace AppBundle\Repository;

/**
 * SolicitudClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
