<?php

namespace AppBundle\Repository;

/**
 * SubastaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubastaRepository extends \Doctrine\ORM\EntityRepository
{
  	public function buildQuery($query, $pg)
  	{
        $query->join('a.propiedad','p');
        $query->addOrderBy("p.titulo", 'ASC');
        $query->join('a.estado','e');
        $query->addOrderBy("e.id", 'ASC');

        if ($titulo = $pg->getFilterValue('titulo')){
            $query->andWhere("UPPER(p.titulo) LIKE UPPER('%".$titulo."%')");
        }
        if ($pg->getFilterValue('estado')){
            $estado = $pg->getFilterValue('estado');
            $query->andWhere("e.id = ".$estado);
        }
        if ($pg->getFilterValue('semana')) {
            $semana = $pg->getFilterValue('semana');
            $query->andWhere("a.semanaReserva = ".$semana);
        }
        if ($pg->orderBy('anio')) {
            $anio = $pg->getFilterValue('anio');
            $query->andWhere("a.anioReserva = ".$anio);
        }
        $query->addOrderBy("a.anioReserva", 'DESC');
        $query->addOrderBy("a.semanaReserva", 'DESC');

  	    return $query;
  	}
    public function publicoQuery($query, $pg)
    {
        $query->join('a.estado', 'e')
              ->andWhere('e.id = 1');
        if ($titulo = $pg->getFilterValue('titulo')){
            $query->join("a.propiedad","p");
            $query->andWhere("UPPER(p.titulo) LIKE UPPER('%".$titulo."%')");
        }
        if ($min = $pg->getFilterValue('montoMin')){
            $query->andWhere("a.ultimoValor >= ".$min);
        }
        if ($max = $pg->getFilterValue('montoMax')){
          
            $query->andWhere("a.ultimoValor <= ".$max);
        }
        return $query;
    }
}
