<?php

namespace AppBundle\Repository;

/**
 * TarjetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarjetaRepository extends \Doctrine\ORM\EntityRepository
{
}
