# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_SUPERADMINISTRADOR: [ROLE_ADMINISTRADOR]
        ROLE_ADMINISTRADOR: [ROLE_COMUN, ROLE_PREMIUM]


    encoders:
        AppBundle\Entity\Usuario: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        usuarios:
            entity:
                class: AppBundle:Usuario
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: usuarios
            form_login:
                login_path: login
                check_path: login
                # success_handler: AppBundle\Security\AuthenticationSuccessHandler
            logout:
                path:   logout
                target: login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMINISTRADOR }
        - { path: ^/superadmin/crear/admin, roles: ROLE_SUPERADMINISTRADOR }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
