<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pg.form_remember' shared service.

include_once $this->targetDirs[3].'/src/PgBundle/Util/Paginator/FormRemember.php';

return $this->services['pg.form_remember'] = new \PgBundle\Util\Paginator\FormRemember(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
