<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4au7jhv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4au7jhv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4au7jhv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4au7jhv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4au7jhv\appDevDebugProjectContainer([
    'container.build_hash' => '4au7jhv',
    'container.build_id' => '504a4854',
    'container.build_time' => 1558043084,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4au7jhv');
