<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKwkmzr3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwkmzr3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKwkmzr3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKwkmzr3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKwkmzr3\appDevDebugProjectContainer([
    'container.build_hash' => 'Kwkmzr3',
    'container.build_id' => '5bd29bad',
    'container.build_time' => 1557856758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwkmzr3');
