<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwfxqtz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwfxqtz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQwfxqtz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQwfxqtz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQwfxqtz\appDevDebugProjectContainer([
    'container.build_hash' => 'Qwfxqtz',
    'container.build_id' => '12954266',
    'container.build_time' => 1560429583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwfxqtz');
